### ISSUE TITLE
Cached calls hang

### ISSUE THREAD

**Issue by lovesh** [tomusdrw/jsonrpc-proxy#172]
I was using this project to only allow whitelisted RPCs to a Substrate node but when I make the same query twice, in my case querying the account balance of the same account, it hangs. The queries don't hang if I run pass the cached method vector as empty to `generic_proxy::run_app` over [here](https://github.com/tomusdrw/jsonrpc-proxy/blob/master/substrate-proxy/src/main.rs#L20) but then I get the transaction priority too low error.
The repeated queries work if I have a delay of the cache eviction timeout, i.e. 3 seconds (as seen [here](https://github.com/tomusdrw/jsonrpc-proxy/blob/master/substrate-proxy/src/main.rs#L68)) after each query which hints that there an issue with caching.

**Comment by tomusdrw** [comment]
Thanks for the report, the library is not really production-tested as of now, so you can expect couple of other errors like this.
Have you considered https://github.com/paritytech/substrate-api-sidecar instead?

The error in cache most likely stems out from using locks in async context, this should probably be rewritten to be lock-free.

**Comment by lovesh** [comment]
Thanks for the reply. Regarding sidecar, heard about it but haven't looked into it. Does it allow sending arbitrary RPC calls and subscribing to storage/extrinsics? 
I have been using this project without any issues so far and that's why wanted to continue but from the potential solution you describe, it might be some time before this gets fixed.

**Comment by tomusdrw** [comment]
> it might be some time before this gets fixed.

Yeah, I don't have enough time currently to take a close look at this. Can only recommend disabling cache for now to work around this issue, sorry!

**Comment by lovesh** [comment]
No worries.
