### ISSUE TITLE
Feature-gate transports

### ISSUE THREAD

**Issue by tomusdrw** [tomusdrw/jsonrpc-proxy#2]
https://github.com/tomusdrw/jsonrpc-proxy/blob/c46bcc63cf20fa02017b7c46ecd835ea1f1f1e38/proxy/transports/Cargo.toml#L8

**Comment by axelchalon** [comment]
We're running *ethereum-proxy* but need to define the features for *transports*

Do we need to somehow pass the features down from *ethereum-proxy* to *generic-proxy* and then from *generic-proxy* to *transports*? Is that possible, or is there a preferable way? How would you see this?

Or is simply defining the features in *transports* good enough for now, and the user just modifies the `default-features` before building?

**Comment by tomusdrw** [comment]
Yeah, I think we need to pass down the features (i.e. `ws = ["generic-proxy/ws"]`) and some way to dynamically get all the transports.

Alternatively transports could be initialised by the `ethereum-proxy` directly and just passed to `generic-proxy`, but I think it's going to be same amount of boilerplate to write.
