### ISSUE TITLE
Alternative implementation: Subway

### ISSUE THREAD

**Issue by xlc** [tomusdrw/jsonrpc-proxy#341]
I would like to let you know that I am working on another generalized and Substrate friendly JSON RPC proxy project: https://github.com/AcalaNetwork/subway

The goal of Subway is pretty much the same as this one. However given the current status of this project so I decided to make a new one with up to date deps instead.

**Comment by tomusdrw** [comment]
Cool stuff, thanks! I'll put a link in the readme and recommend using `subway` instead.
